### PR TITLE
Fixed Issues #11 and #12

### LINKED ISSUE #11: Numeric inputs other than age aren't validated before uploading
If the age question isn't in the expected range, the user cannot submit their answer. However, for other dynamically added questions with numeric input this isn't true. The dynamically specified input range isn't respected.

We need to add some way so new questions with numeric input are validated to be in their defined possible range. If they aren't, the user shouldn't be able to submit their answers.

### LINKED ISSUE #12: Somehow notify user when they enter an invalid input
Currently when a user enters invalid input, they have now way to know their input is invalid. Their only indication is being unable to submit their form.

In addition to preventing users from submitting invalid forms, they should be notified immediately if their input isn't valid, so they know which one of their answers is problematic.

### PR DESCRIPTION
**Pull request by StatisMike**
Fix #12:

- added reactiveValues object `valid` to store outputs of `valid$minmax_matched` and `valid$mandatory_filled` (before: `mandatoryFilled`)
* checks if `submit` actionButton can send results on the googlesheet
* generation of error message if user try to send results while there are some things not right
- actionButton isn't disabled anymore when inputs are invalid: it's label now shows "Can't submit", and after clicking it the modalDialog shows up listing which inputs are problematic

Fix #11:

- added `fieldsNumeric` object to store numericInputs' IDs 
- added `valid$minmax_matched` similiar to `valid$mandatory_filled` to store information if the input is within `num_min` and `num_max` range

### CODE REVIEW

File: shiny/server.R [hunk 1]
```diff
@@ -9,41 +14,85 @@ server <- function(input, output, session) {
...
-    # age is not between 13 and 100
-    shinyjs::toggleState(
-      id = "submit",
-      condition = mandatoryFilled && input$age >= 13 && input$age <= 100
-    )
+    # update submit button if any mandatory fields are not filled in and
+    # numeric inputs are in their valid min-max values - instatenous feedback
+    # can't be disabled - need to be able to trigger modalDialog with info
+
+    if(!all(valid$mandatory_filled) || !all(valid$minmax_matched)){
```
Comment (eshom) [inline shiny/server.R:39]: It's common style to add spaces after if statements.
`if (!all(valid$mandatory_filled) || !all(valid$minmax_matched)){`

File: shiny/server.R [hunk 2]
```diff
@@ -9,41 +14,85 @@ server <- function(input, output, session) {
...
-      shinyjs::html("error_msg", err$message)
-      shinyjs::show(id = "error", anim = TRUE, animType = "fade")
-    },
-    finally = {
-      shinyjs::enable("submit")
-      shinyjs::hide("submit_msg")
-    })
+    
+    if(!all(valid$mandatory_filled) || !all(valid$minmax_matched)){
+
```
Comment (eshom) [inline shiny/server.R:57]: I like the new submit buttons that inform users when there are problems in some fields. The only thing that would be nice to add is field highlighting. Something like a simple red border on wrong fields. I assume that's possible with `shinyjs()`?

File: shiny/server.R (hunk 1 above)
Comment (eshom) [reply shiny/server.R:39]: More petty style comments (sorry):
1) This is probably an IDE thing. But there are empty lines with whitespaces. If you could trim those that would be nice.
2) I noticed this check `!all(valid$mandatory_filled) || !all(valid$minmax_matched)` repeats. Could you make that into a variable, or would that ruined the reactivity?

Comment (StatisMike) [reply shiny/server.R]: I wasn't aware of the spaces convention. Whitespaces are removed and new variable in `valid` added: `valid$filled_matched`, which concatenates both `valid$mandatory_filled` and `valid$minmax_matched`.

File: shiny/server.R (hunk 2 above)
Comment (StatisMike) [reply shiny/server.R]: Done - the answers are now outlined too. The style can be further customized via change of CSS class `invalid_input` in 'constants.R' file by someone more knowledgable in CSS :)

Comment (StatisMike) [reply shiny/server.R]: Changed the logic so after the first submit button click the outlines start to show, and after that they will be disappearing when the inputs are valid.

**Review by eshom — APPROVED** [review]
